// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/spf13/viper"
	"piyo-engine/internal/handler"
	"piyo-engine/internal/repository"
	"piyo-engine/internal/server"
	"piyo-engine/internal/service"
	"piyo-engine/pkg/app"
	"piyo-engine/pkg/jwt"
	"piyo-engine/pkg/log"
	"piyo-engine/pkg/server/http"
	"piyo-engine/pkg/sid"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	handlerHandler := handler.NewHandler(logger)
	db := repository.NewDB(viperViper, logger)
	repositoryRepository := repository.NewRepository(logger, db)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	teamRepository := repository.NewTeamRepository(repositoryRepository)
	teamService := service.NewTeamService(serviceService, teamRepository)
	teamHandler := handler.NewTeamHandler(handlerHandler, teamService)
	httpServer := server.NewHTTPServer(logger, viperViper, jwtJWT, userHandler, teamHandler)
	job := server.NewJob(logger)
	appApp := newApp(httpServer, job)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewTransaction, repository.NewUserRepository, repository.NewTeamRepository, repository.NewUserTeamRoleRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewTeamService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewTeamHandler)

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJob)

// build App
func newApp(
	httpServer *http.Server,
	job *server.Job,

) *app.App {
	return app.NewApp(app.WithServer(httpServer, job), app.WithName("demo-server"))
}
